# SPDX-FileCopyrightText: OpenTalk Team <mail@opentalk.eu>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
#
SPDX-PackageDownloadLocation = "https://git.opentalk.dev/opentalk/backend/libs/service-probe"
SPDX-PackageName = "service-probe"
SPDX-PackageSupplier = "OpenTalk Team <mail@opentalk.eu>"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "OpenTalk Team <mail@opentalk.eu>"
SPDX-License-Identifier = "MIT OR Apache-2.0"
path = ["CHANGELOG.md", "Cargo.lock", "README.md", "renovate.json"]
precedence = "aggregate"
